### ISSUE TITLE
Tremblement de l'interface graphique

### ISSUE THREAD

**Issue by Rayghun** [Grolash/Projet-Info-BAB1-MICHEL-SURIN#21]
Dans la colonne la plus à droite, si on tient un mur vertical, l'interface graphique "tremble" (le plateau de jeu se déplace rapidement de droite à gauche).

**Comment by VirgilSurin** [comment]
> 
> 
> Dans la colonne la plus à droite, si on tient un mur vertical, l'interface graphique "tremble" (le plateau de jeu se déplace rapidement de droite à gauche).

Peut-être dû à la taille des sprites des murs et/ou du sprites du mur fantôme

**Comment by Rayghun** [comment]
Alors petite précision, après quelques tests, il semble qu'il s'agisse en fait de 2 bugs.
Premièrement, sur les extrémités du plateau de jeu (lignes et colonnes SAUF la ligne du bas), si on fait passer un mur de la position verticale à la position horizontale, le plateau de jeu se décale légèrement.
Deuxièmement, dans le cas très précis où l'adversaire est presque bloqué (il ne reste qu'un mur à poser pour le bloquer) et où ce mur se trouve jute à côté d'une des extrémités buguées (haut, gauche, droite), lorsqu'on tient un mur dans une des extrémités et qu'on le fait glisser de manière à enfermer l'adversaire, le jeu tremble violemment.
(Oui c'était précis)

**Comment by VirgilSurin** [comment]
Le deuxième bug semble avoir été fix

**Comment by VirgilSurin** [comment]
Fix, des sprites plus petits on été mis en place.
