### ISSUE TITLE
Bug de la gauche du plateau

### ISSUE THREAD

**Issue by Rayghun** [Grolash/Projet-Info-BAB1-MICHEL-SURIN#22]
Lorsqu'on tient un mur et qu'en maintenant la souris, on déplace la souris à gauche de l'écran (en dehors du plateau), le jeu lance une exception (visible dans le terminal) mais ne plante pas.

**Comment by VirgilSurin** [comment]
En effet il manquait une condition pour rejeter le cas où la coordonnée de la souris était < 0 sur les X
