### ISSUE TITLE
La croix ne ferme pas l'interface

### ISSUE THREAD

**Issue by Rayghun** [Grolash/Projet-Info-BAB1-MICHEL-SURIN#24]
Dans le menu principal, si une partie a déjà été démarrée depuis le lancement du jeu, si on clique sur "Launch game!" et qu'ensuite, dans la boîte de dialogue "Launch confirmation" on clique sur la croix, plutôt que de revenir sur le menu, une partie se lance.

**Comment by VirgilSurin** [comment]
se produit lorsqu'une partie à déjà été lancée au préalable

**Comment by VirgilSurin** [comment]
Fixed
la croix de la ConfirmBox ne changeait pas l'état de la réponse. Il restait donc sur le oui
