### ISSUE TITLE
Les joueurs peuvent se superposer

### ISSUE THREAD

**Issue by Rayghun** [Grolash/Projet-Info-BAB1-MICHEL-SURIN#25]
Plusieurs joueurs peuvent se retrouver sur la même case (se passe en mode 4 joueurs).
Exemple (le joueur est le personnage en bas à droite, les autres sont des IA easy).
![Capture d’écran (1422)](https://user-images.githubusercontent.com/60981139/81476143-7b100180-9210-11ea-891b-0487c37467a2.png)
Autre exemple (le joueur est cette fois le personnage en haut à droite). On remarque d'ailleurs que deux IA ont déjà fusionné.
![Capture d’écran (1423)](https://user-images.githubusercontent.com/60981139/81476175-b3afdb00-9210-11ea-8561-004c9416ed17.png)

**Comment by VirgilSurin** [comment]
should be fixed with the new move
