### ISSUE TITLE
Echec de sauvegarde

### ISSUE THREAD

**Issue by Rayghun** [Grolash/Projet-Info-BAB1-MICHEL-SURIN#30]
La sauvegarde ne fonctionne plus.
Elle lance une exception dans le terminal (sans pour autant faire crasher le jeu). Le terminal lance une "java.io.FileNotFoundException: .\misc\saves\Save.data (Le chemin d'accès spécifié est introuvable)"
De plus, si on demande au jeu de lancer la sauvegarde, il ne la trouve pas.
![Capture d’écran (1440)](https://user-images.githubusercontent.com/60981139/81507018-8a6b7980-92fa-11ea-8f66-f4f64105290d.png)

**Comment by VirgilSurin** [comment]
normalement réglé
